### ISSUE TITLE
Tutorials fail with many "../bin/libHalide.so: undefined reference..." errors

### ISSUE THREAD

**Issue by mcragun** [halide/Halide#2290]
I'm trying to run the Halide tutorials and am getting a large amount of errors from tutorial 2 onwards (any that #include <libHalide.so>) when I try and compile.  There were no errors during the build process and all of the tests complete successfully.  The errors are shown below (I have attached the entire output, but it's really long).  It's likely something simple on my end.  

I am running Ubuntu 16.04, gcc 5.4, llvm 3.8.  Any thoughts would be appreciated.

[Halide_error.txt](https://github.com/halide/Halide/files/1247126/Halide_error.txt)

/tmp/ccTJbjo2.o: In function `Halide::Internal::check_introspection(void const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
/home/mcragun/Halide/tutorial/../include/Halide.h:413: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/mcragun/Halide/tutorial/../include/Halide.h:413: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/mcragun/Halide/tutorial/../include/Halide.h:415: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/mcragun/Halide/tutorial/../include/Halide.h:414: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/mcragun/Halide/tutorial/../include/Halide.h:413: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/tmp/ccTJbjo2.o:/home/mcragun/Halide/tutorial/../include/Halide.h:417: more undefined references to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()' follow
/tmp/ccTJbjo2.o: In function `HalideIntrospectionCanary::test_a(void const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/mcragun/Halide/tutorial/../include/Halide.h:456: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/mcragun/Halide/tutorial/../include/Halide.h:456: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/mcragun/Halide/tutorial/../include/Halide.h:456: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
....
../bin/libHalide.so: undefined reference to `std::basic_ifstream<char, std::char_traits<char> >::basic_ifstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'
../bin/libHalide.so: undefined reference to `std::_V2::error_category::_M_message[abi:cxx11](int) const@GLIBCXX_3.4.21'
../bin/libHalide.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
../bin/libHalide.so: undefined reference to `std::_V2::generic_category()@GLIBCXX_3.4.21'
../bin/libHalide.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const@GLIBCXX_3.4.21'

**Comment by mcourteaux** [comment]
I believe you are using a precompiled .so file, and linking against a different standard library. (glibc++). How are you compiling?

**Comment by mcragun** [comment]
@mcourteaux Thanks for the response.

My workflow is as follows on Ubunutu 16.04, gcc-5.4:

1.  Download amd compile llvm3.8 according to instructions in git Readme
2. Add llvm/clang to path as in Readme
3. git clone Halide repo
4.  cd Halide
5. make --> This works with no errors output
6. make run_tests --> most tests pass, but bin/correctness_image_io fails with similar errors as above
7. make run_apps --> all fail with errors similar to above

The tutorials also fail.  The compile string that I am using is straight copy/paste out of the tutorials.  I have done the same process on a different workstation and it all seems to work, so I think it's something about my environment that is causing problems.

Thanks

**Comment by mcragun** [comment]
I installed Ubuntu 14.04 and mirrored the env I had on a previous system that worked.  Everything now works with gcc 4.8, llvm-3.8.  I'm going to close the ticket because I don't think it was Halide's fault.

**Comment by lianera** [comment]
Got same errors too. I found the reason is that halide is built with clang while source file is compiled with gcc. Just simply use clang to build the source, it works.

**Comment by khourig** [comment]
Leaving this here for others to find. Ubuntu 14 gcc defaulted to the old ABI version and Ubuntu 16 gcc defaults to the new one. Please see https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html
