### PR TITLE
Fix some Variable alignment propagation in the simplifier.

### LINKED ISSUE #9328: add_requirement() fails to transitively infer alignment
As #9327 is a problem, I was playing around with `add_requirement()` and set the alignment of extents, while equating stride to extents of lower dimensions to promise dense storage, like so:

```cpp

      add_requirement(output.dim(0).extent() % bsx == 0);
      add_requirement(output.dim(1).extent() % bsy == 0);
      add_requirement(output.dim(1).stride() == output.dim(0).extent());
      add_requirement(output.dim(2).stride() == output.dim(0).extent() * output.dim(1).extent());

```

This emits the proper asserts 1 to 1. However, the generated code still seemed to not understand that `output.dim(1).stride()` must have the same alignment as `output.dim(0).extent()`, despite the fact that I required them to be equal.

Manually adding:

```cpp
      add_requirement(output.dim(1).stride() % bsx == 0);
      add_requirement(output.dim(2).stride() % (bsx * bsy) == 0);
```
Clearly helped the generated code see more of the alignment. This should have been inferred automatically.

### PR DESCRIPTION
**Pull request by mcourteaux**
`learn_true(x == y)` with x and y vars did not fuse their alignment and bounds info.

Fixes #9328.
~Partial resolution for #9327 by adding `const` which avoids accidental assignment.~

## Breaking changes

None I'm aware of.

## Checklist

- [ ] Tests added or updated (not required for docs, CI config, or typo fixes)
- [ ] Documentation updated (if public API changed)
- [ ] Python bindings updated (if public API changed)
- [ ] Benchmarks are included here if the change is intended to affect performance.
- [ ] Commits include AI attribution where applicable (see Code of Conduct)

### CODE REVIEW

**Comment by alexreinking** [comment]
Can you add a regression test somewhere?

**Comment by alexreinking** [comment]
`clang-tidy` rejects the const-return-value trick. Please drop that commit for this PR; I'm still on the fence about whether I'd like to use a proxy object anyway.

**Comment by abadams** [comment]
Apparently it's preferred to forbid operator= on rvalues on the type in question, rather than return const things (which breaks moving from them). E.g in struct Expr:

```
Expr &operator=(const Expr &) & = default;
```

Note the final `&`, which prevents assigning to rvalue Exprs.

**Review by abadams — APPROVED** [review]

**Comment by mcourteaux** [comment]
> Can you add a regression test somewhere?

Oops. Working on the regression test. Building on top of your correctness_vector_store_alignment. 

UPDATE: regression test added in #9337.

**Comment by mcourteaux** [comment]
I'd argue the clang-tidy warning is just dumb?

> /home/runner/work/Halide/Halide/src/Dimension.cpp:47:1: error: return type 'const Expr' is 'const'-qualified at the top level, which may reduce code readability without improving const correctness [readability-const-return-type,-warnings-as-errors]
> ```
>    47 | const Expr Dimension::stride() const {
>       | ^~~~~
> ```
> Error: return type 'const Expr' is 'const'-qualified at the top level%2C which may reduce code readability without improving const correctness
> 

It _does_ improve const correctness.



> `Expr &operator=(const Expr &) & = default;`

I guess you meant `= delete`, @abadams ?
