### ISSUE TITLE
Fail to build test apps

### ISSUE THREAD

**Issue by fycus-tree** [halide/Halide#1112]
Trying to use the Makefile to build on Ubuntu 16.04 Beta2 (LLVM = 3.8, GCC=5.3)

Building Halide works fine but looks like it requires a -lncurses link
`make test_apps`

returns
`g++ -std=c++11 -I /home/fycus/Halide/include/ -I /home/fycus/Halide/tools/ -I /home/fycus/Halide/apps/support/ bilateral_grid.cpp -g /home/fycus/Halide/lib/libHalide.a -o bilateral_grid -lz  -ldl -lpthread -lz \

/home/fycus/Halide/lib/libHalide.a(llvm_745_Process.cpp.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0x82): undefined reference to`setupterm'
/home/fycus/Halide/lib/libHalide.a(llvm_745_Process.cpp.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0xa8): undefined reference to`tigetnum'
/home/fycus/Halide/lib/libHalide.a(llvm_745_Process.cpp.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0xb1): undefined reference to`set_curterm'
/home/fycus/Halide/lib/libHalide.a(llvm_745_Process.cpp.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0xb9): undefined reference to`del_curterm'
`

**Comment by abadams** [comment]
We compile llvm without terminfo usually. You'll probably need to jam
-lterminfo in a few choice places if you have an llvm with terminfo.

I should really update the Makefile to account for this. I'll assign this
issue to myself to remember to do this.

**Comment by rzhuyue** [comment]
sorry, i'm a beginner for llvm. I want to know where to set the -lterminfo flag?

**Comment by abadams** [comment]
In apps/support/Makefile.inc, try changing:

LDFLAGS += -ldl -lpthread -lz

to:

LDFLAGS += -ldl -lpthread -lz -lterminfo

If that fails, grep for everywhere we use "-lpthread" and add -lterminfo
alongside it.

**Comment by rzhuyue** [comment]
thank you~it works

**Comment by ariesgun** [comment]
I get the same issue here. I have tried to add -lterminfo into the Makefile, but I get the following error.

`
g++ -std=c++11 -I /home/x/project/Halide/include/ -I /home/x/project/Halide/tools/ -I /home/x/project/Halide/apps/support/ -g -fno-rtti bilateral_grid_generator.cpp /home/x/project/Halide/lib/libHalide.a /home/x/project/Halide/tools/GenGen.cpp -o bin/bilateral_grid_exec  -ldl -lpthread -lz -lterminfo
/usr/bin/ld: cannot find -lterminfo
`

Tried to search/ install libterminfo, but failed to find one.

Any idea?

**Comment by kgnk** [comment]
Try -ltinfo

**Comment by jrk** [comment]
@steven-johnson @abadams I was reminded of this again recently.

This *should* be getting caught by `llvm-config --system-libs` everywhere in our Makefiles, but it still seems to come up frequently. I believe in this case `apps/support/Makefile.inc` does set up an `LLVM_LDFLAGS` variable correctly, but most apps never use it. I'm looking further now.

In general, though, it seems like we could do something smarter on our side to keep this dance from constantly happening. Obvious options:

- Embed libtinfo.a into our static binary (iff required by the LLVM being linked)
- Have our own `halide-config` tool for setting the appropriate LDFLAGS, given the corresponding built Halide
- Always build our binary releases with LLVM terminfo support disabled. It seems we already do this, but is it enforced intentionally, or just a happy accident?

**Comment by SoYman** [comment]
After dealing with this problem for quite a while on an Arch Linux setup the solution was to install libtinfo from the AUR and inserting -ltinfo alongside each instance of -lpthread. In case anyone stumbles upon this.

**Comment by steven-johnson** [comment]
@jrk In general, using `llvm-config --system-libs` correctly is necessary to make things work well anyway. 

For Makefiles we often don't notice since the usage is all on Unixy systems, where the only likely odd man out is terminfo; however, getting `--system-libs` wrong in CMake or Bazel can be a nightmare of wrongness, because Windows.

Fortunately, the Bazel ruleset handles `llvm-config --system-libs ` correctly as of now, and soon, the CMake ruleset will as well.

**Comment by dherring** [comment]
sources: Halide-release_2018_02_15.tar.gz
OS: 64-bit Debian 9.3
GCC: gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
LLVM: 5.0.1
Clang: clang version 5.0.1-2~bpo9+1 (tags/RELEASE_501/final)

I had a similar compilation issue.  Fixed it by editing the top-level Makefile to link test/internal.cpp against curses.

    TEST_LD_FLAGS = -L$(BIN_DIR) -lHalide $(COMMON_LD_FLAGS) -lcurses

Other edits to configure the Makefile for my environment:

    LLVM_CONFIG ?= llvm-config-5.0
    CLANG ?= clang-5.0

**Comment by r-barnes** [comment]
@dherring's solution was necessary for me to compile `Halide-release_2018_02_15` on Ubuntu 18.04.1 with clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final).

**Comment by alexreinking** [comment]
Closing because this issue is stale (LLVM < 8.0 is no longer supported)
