### ISSUE TITLE
Func name "head1_filter.extent.0_d__" is invalid. Func names may not contain the character '.', as it is used internally by Halide as a separator

### ISSUE THREAD

**Issue by OuHangKresnik** [halide/Halide#4010]
When I tried to compile autoscheduler, such error occurs.

Linux Platform

HL_PERMIT_FAILED_UNROLL=1 ../autoscheduler/bin/cost_model.generator -g train_cost_model -o ../autoscheduler/bin/cost_model -f train_cost_model target=host-no_runtime auto_schedule=false -e stmt,static_library,h,assembly

**Comment by OuHangKresnik** [comment]
Does anyone know what's happening here ? I'm the first time to try this out.

**Comment by thiesmoeller** [comment]
Did a git a bisect run ...:

```
46abc24b8a62cd7d3d58ac066df8896201208485 is the first bad commit
commit 46abc24b8a62cd7d3d58ac066df8896201208485
Author: Tzu-Mao Li <tzumao@mit.edu>
Date:   Mon Jul 8 17:32:37 2019 -0400

    Allow taking derivative with respect to Param

```

**Comment by OuHangKresnik** [comment]
Thank you @thiesmoeller  I will try this out today.

**Comment by BachiLi** [comment]
: ( I'll take a look

**Comment by OuHangKresnik** [comment]
After I roll back to 6e99decbf0876bcfbf856d86afe6d76fe4019a7e, the one just before 46abc24b8a62cd7d3d58ac066df8896201208485, the compilation still fails:

../autoscheduler/train_cost_model.cpp:358:0: error: ignoring #pragma omp parallel [-Werror=unknown-pragmas]
             #pragma omp parallel for
 ^
cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]

Not enable openmp ? -fopenmp  in ./support/Makefile.inc

**Comment by thiesmoeller** [comment]
use clang.
This was fixed later..

ouhang <notifications@github.com> schrieb am Mi., 17. Juli 2019, 09:01:

**Comment by OuHangKresnik** [comment]
what libpng and libz version number does Halide use ?

**Comment by OuHangKresnik** [comment]
Also, when I tried to run:

Now make -j32 autotune has passed, but

make -j32 demo in apps/autoscheduler is failed

bin/host/demo.registration.cpp: In constructor ‘halide_nsreg_demo::{anonymous}::Registerer::Registerer()’:
bin/host/demo.registration.cpp:29:75: error: ‘nullptr’ was not declared in this scope
         halide_register_argv_and_metadata(::demo_argv, ::demo_metadata(), nullptr);

**Comment by OuHangKresnik** [comment]
Just be curious, what's the difference between:

apps/autotune and auto scheduler examples in tutorial

**Comment by steven-johnson** [comment]
Any recent version should be fine.

**Comment by abadams** [comment]
nullptr not being resolved indicates you have an old compiler and it's not
in c++11 mode by default. Try adding -std=c++11

**Comment by OuHangKresnik** [comment]
The two versions should match.
For example, libpng-1.6.32 couldn't match with zlib-1.2.11 or zlib-1.2.9 (I've tried this two)

**Comment by steven-johnson** [comment]
Should be fixed by #4016
