### ISSUE TITLE
Compilation error on aarch64-linux: '_Float16' was not declared in this scope; did you mean '_Float64'

### ISSUE THREAD

**Issue by twesterhout** [halide/Halide#7785]
Halide 16.0.0 fails to compile on aarch64-linux on GCC 12.3.0:

```
In file included from /build/source/build/include/HalideBuffer.h:30,
                 from /build/source/src/autoschedulers/anderson2021/Weights.h:9,
                 from /build/source/src/autoschedulers/anderson2021/weightsdir_to_weightsfile.cpp:6:
/build/source/build/include/HalideRuntime.h:2040:61: error: '_Float16' was not declared in this scope; did you mean '_Float64'?
 2040 | HALIDE_ALWAYS_INLINE constexpr halide_type_t halide_type_of<_Float16>() {
      |                                                             ^~~~~~~~
      |                                                             _Float64
/build/source/build/include/HalideRuntime.h:2040:46: error: template-id 'halide_type_of<<expression error> >' for 'constexpr halide_type_t halide_type_of()' does not match any template declaration
 2040 | HALIDE_ALWAYS_INLINE constexpr halide_type_t halide_type_of<_Float16>() {
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~
/build/source/build/include/HalideRuntime.h:2029:46: note: candidate is: 'template<class T> constexpr halide_type_t halide_type_of()'
 2029 | HALIDE_ALWAYS_INLINE constexpr halide_type_t halide_type_of() {
      |                                              ^~~~~~~~~~~~~~
```

See https://logs.ofborg.org/?key=nixos/nixpkgs.250545&attempt_id=35266673-36bc-4371-b6c8-54603759a1c9 for the full log.

According to GCC docs, we should use `__fp16` instead of `_Float16` on ARM (source https://gcc.gnu.org/onlinedocs/gcc/Half-Precision.html).

Would it make sense to introduce something like `halide_float16_t` as an alias for `_Float16` or `__fp16` depending on the architecture?

**Comment by steven-johnson** [comment]
> According to GCC docs, we should use `__fp16` instead of `_Float16` on ARM (source https://gcc.gnu.org/onlinedocs/gcc/Half-Precision.html).

This link also says: **It is recommended that portable code use the _Float16 type defined by ISO/IEC TS 18661-3:2015. See [Additional Floating Types](https://gcc.gnu.org/onlinedocs/gcc/Floating-Types.html).**

HalideRuntime.h is intended as portable code.

**Comment by twesterhout** [comment]
aarch64-darwin builds fine: https://logs.ofborg.org/?key=nixos/nixpkgs.250545&attempt_id=84a68c07-fc82-44cf-a6ff-5c73a1e0b7e2
So I'm tempted to conclude that the issue is gcc-specific.

In the meantime, I'll see if I can disable float16 support on aarch64-linux when building Halide in Nixpkgs.

**Comment by russell-taylor** [comment]
I ran into this same problem just now on a Raspberry Pi 5 while trying to build either the current source or 17.0.2 to get Vulkan beta support. (It fails with or without TARGET_VULKAN=ON.)  I'm using GCC version 12 and LLVM version 16.

Any more thoughts on how to get this to work? Anyone gotten this compiling on Raspberry Pi?

Here are the build instructions I made for myself:

To use Halide on a Raspberry Pi:

    sudo apt install clang-tools-16 clang-16 libclang-16-dev lld-16 liblld-16-dev
    sudo ln -s /usr/bin/clang-16 /usr/bin/clang
    sudo ln -s /usr/bin/llvm-config-16 /usr/bin/llvm-config

# Building

Building Halide on Rasperry Pi:

    mkdir -p ~/src/
    cd ~/src
    git clone https://github.com/halide/Halide.git
    cd Halide
    git checkout v17.0.2
    mkdir -p ~/build/halide
    cd ~/build/halide
    cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DTARGET_VULKAN=ON -DTARGET_WEBASSEMBLY=OFF -DLLVM_DIR=/usr/lib/llvm-16/lib/cmake/llvm -S ~/src/Halide -B build
    cmake --build build

**Comment by russell-taylor** [comment]
When I added a link for clang++ and then used `CC=/usr/bin/clang CXX=/usr/bin/clang++` on the cmake configuration line so that it built using clang rather than GCC, it got past this error. So that's a workaround for me.

**Comment by abadams** [comment]
> [!NOTE]
> **Automated triage:** this issue was flagged by Claude as likely safe to close, for the reason below. The reasoning was checked against the current source, and a second pass tried and failed to refute it, but no human verified this specific text. **If the reason is wrong, please reopen the issue and say so** — some fraction of these are expected to be wrong.

**Reason (CLOSE_FIXED):** The failure was `HalideRuntime.h` unconditionally declaring `halide_type_of<_Float16>()` on GCC 12 / aarch64, where C++ has no `_Float16`. The detection logic now gates `HALIDE_CPP_COMPILER_HAS_FLOAT16` on GCC >= 13 for aarch64 (and GCC >= 13 with `__ARM_FP16_FORMAT_IEEE` for 32-bit arm), so GCC 12.3 on aarch64 no longer takes that path.

**Evidence:** `src/runtime/HalideRuntime.h:121-132` (`#if defined(__GNUC__) && (__GNUC__ >= 12)` with `(defined(__aarch64__) && (__GNUC__ >= 13))`); commits `b87f2b1a7` "Fix _Float16 detection on ARM64 GCC\<13 (#8401)", `36c499077` (#8987, makes the macro overrideable), `5bceffd1a` (#9189).

Fixed: `_Float16` support is now feature-detected rather than assumed, and aarch64 GCC \< 13 (the compiler in the original report, and the Raspberry Pi GCC 12 case) is excluded — see `src/runtime/HalideRuntime.h:121-132` and #8401. `HALIDE_CPP_COMPILER_HAS_FLOAT16` can also be overridden explicitly (#8987). Closing.
