### ISSUE TITLE
Incorrect results using Metal

### ISSUE THREAD

**Issue by shoaibkamil** [halide/Halide#2425]
The repository [here](https://github.com/shoaibkamil/halide_metal_error) contains a standalone AOT testcase that gives incorrect results on Metal targets on some machines.  Changing the target to OpenCL generates almost exactly the same shader but gives correct results.

@zvookin or anyone else with some Metal experience, please take a look.  I've verified:

1) this is not due to LICM 
2) the parameters passed into the shader by `halide_metal_run()` appear correct
3) incorrect results occur on two test machines: Mac Pro 2013, macOS 10.12.6 and Macbook Pro 15" 2016, 10.12.6.  I get correct results on my Macbook Pro 13" 2017, 10.13.

@slomp please add any details I may have missed

**Comment by slomp** [comment]
This pretty much sums up the bulk of our investigation.
Besides that, the only thing I think it is worth mentioning is our current workaround:
if we replace `select()` calls by a binary lerp-like expression, we get the correct result.
I take this as more evidence that the data and parameters are being correctly passed to the shader.

**Comment by zvookin** [comment]
I will take a look.

-Z-

**Comment by tqchen** [comment]
We experienced a similar problem when providing code generator in [TVM](https://travis-ci.com/dmlc/tvm) and it was caused by the index type of the thread index in Metal is unsigned and having expression doing the subtraction to negative value causes the problem. An explicit cast to int type is always needed to resolve this issue

**Comment by shoaibkamil** [comment]
@tqchen Thanks for the suggestion.  The Halide-generated Metal shader does seem to do an implicit cast, but when I insert explicit casts, it does not change the erroneous result.

I can confirm that the code gets correct results if I modify the `Load`/`Store` codegen to use `max(0, <index id>)` for the index for the load/store.  However, we're still looking into what is the actual cause, since it doesn't seem like the index should ever be negative if the passed-in parameters are correct.

**Comment by tqchen** [comment]
Just to be clear, the error we encountered was not due to the index value in load/store become negative, but due to the problem in the condition. When we have something like 
```c++
select( i <  threadIdx - 100, a, b)
```
since ```threadIdx``` is unsigned int, the result ```threadIdx - 100``` will always be unsigned int (and there is an underflow), this causes the select condition to be incorrectly evaluated. We solved it by always explicit cast when referring to thread index.
```c++
select( i <  ((int)threadIdx) - 100, a, b)
```

**Comment by zvookin** [comment]
I'll try to look at it today. I doubt we've been particularly careful about
the signedness of the loop index special vars in any of the GPU APIs.

-Z-

**Comment by zvookin** [comment]
I should add I did pull this and started looking at it earlier this week. I
haven't yet repro'ed the failure so it was going to require finding a way
to do that.

-Z-

**Comment by shoaibkamil** [comment]
Here's the generated shader, in case it's useful: https://gist.github.com/shoaibkamil/a23a6c9804157467552cfac32c8aa087

Note that I've slightly modified the codegen to explicitly cast the loop variables.

**Comment by khourig** [comment]
When working with unsigned values, i always phrase expressions like that as `select(i + 100 < threadIdx, a, b)`

**Comment by zvookin** [comment]
I have reproduced the error. It looks like every third three component pixel is all zero. I'll try to debug it some more, but it is starting to look like a Metal compilation error not a bug or undefined behavior in our shader. I don't see anyway this could be a signed/unsigned error on the thread/block indices as we assign them to int variables and never use the Metal kernel parameter directly. Thus they should always be signed.

(It also doesn't look to be an error with copy back or synchronization, though I suppose the execution order could have ever third pixel getting written later somehow. But I think Occam's razor eliminates that possibility...)

**Comment by slomp** [comment]
I adapted the generated shader code to C and emulated the block/thread/loop functionality, inserted plenty of asserts, and was unable to find any issue.

Given that it works on macOS 10.13, it could be some driver or alignment issue when uploading the buffer information. Unfortunately, there does not seem to be a way to use the Metal GPU Frame Capture functionality on 10.12.x that would allow us to inspect the data the shader is actually seeing...

@shoaibkamil out of curiosity, does your MacBookPro 13/2017 has an integrated GPU or a discrete one?

**Comment by zvookin** [comment]
The buffer is page aligned. The only notable thing is it is stride 4 and
extent 3 on the channels, which means the upload and download are a long
series of 3 byte memcpys. But that shouldn't present difficulties for the
shader.

-Z-

**Comment by shoaibkamil** [comment]
@zvookin Thanks for taking a look.  I agree that this looks like a bug on Apple's part (whether it's a Metal compiler bug or a runtime bug with odd stride memcpys).  I plan on testing on a Mac Pro with macOS 10.13 to see if it was fixed, and subsequently filing a bug with Apple.  

@slomp My MBP13 has an integrated GPU.

**Comment by slomp** [comment]
@zvookin I was referring to the hidden generated constant buffer in which parameters like mins, extents and strides are passed.

@shoaibkamil
If we file the bug report, I guess we should provide Apple with a list of systems where it occurs:
mine is: macOS 10.12.6, MacBook Pro (15-inch, 2016), Intel HD Graphics 530 1536 MB

**Comment by zvookin** [comment]
The system I am seeing the issue on is a Mac Pro running 10.12.2 with an AMD FirePro D300 GPU.

**Comment by slomp** [comment]
quick update: after upgrading to macOS 10.13, the issue no longer manifests here.

**Comment by slomp** [comment]
Another update: after XCode upgraded itself on my system running macos 10.12, XCode also upgraded the macosx SDK to 10.13; the problem appears to have gone away with the new SDK, even though I am still running 10.12.

**Comment by shoaibkamil** [comment]
It appears that  #2634 may have fixed this.  @slomp, can you confirm with this testcase on 10.12?

**Comment by slomp** [comment]
Sure, I'll test it.
We're talking about this specific commit, correct?
https://github.com/halide/Halide/commit/529702b47d114e0ee5b5349547f3cea4266e7ac0

**Comment by shoaibkamil** [comment]
@slomp yes, though I would just check with current trunk for sanity's sake.

**Comment by slomp** [comment]
@shoaibkamil The results (metal vs cpu) are still inconsistent. :/
