### PR TITLE
[Hexagon] Fix for LUT32 correctness.

### PR DESCRIPTION
**Pull request by aankit-ca**
**Do NOT merge.**

Lower bound for lut needs to > -1 instead of >= -1.
The bug was introduced in b7dd787c4532d759334f0a2348c993af5e21f152 commit.
@dsharletg @pranavb-ca  The lut32 test fails right now with a compilation error.

### CODE REVIEW

**Comment by steven-johnson** [comment]
See https://github.com/halide/Halide/pull/5199 for testing

**Comment by steven-johnson** [comment]
This has injected a new failure that isn't in current trunk; `correctness_gather` now fails for the host-hvx_128 target with

Hexagon simulator executed function 0x5b750 in 2000 cycles
Hexagon simulator executed function 0x60cd0 in 2000 cycles
Hexagon simulator executed function 0x637c0 in 2000 cycles
Hexagon simulator executed function 0x877c0 in 2000 cycles
correctness_gather: /usr/local/google/home/srj/GitHub/llvm-project/trunk/llvm/include/llvm/CodeGen/ValueTypes.h:261: llvm::MVT llvm::EVT::getSimpleVT() const: Assertion `isSimple() && "Expected a SimpleValueType!"' failed.
bash: line 1: 413375 Aborted                 /usr/local/google/home/srj/GitHub/Halide/bin/correctness_gather

**Comment by aankit-ca** [comment]
@steven-johnson Yes Steven. Unfortunately this code path was tested only by the correctness_gather testcase which was commented out earlier. I'm working on a fix for the error.

**Comment by aankit-ca** [comment]
@steven-johnson  Can you test this patch again. The relevant LLVM patch has been merged upstream.

**Comment by abadams** [comment]
Steven's away. I have told the buildbots to rerun the failing tests. I *think* that means they'll pull a fresh trunk llvm.

**Comment by aankit-ca** [comment]
Do the buildbots test for host-hvx128?

**Comment by steven-johnson** [comment]
Clone is clean! Landing.
